; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

; --- Common settings for hardware environments ---
[common]
build_flags =
    -Wall
    -Wextra
monitor_speed = 115200

[env]
test_framework = unity

; --- Hardware target ---

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
build_flags = ${common.build_flags}
monitor_speed = ${common.monitor_speed}

; --- Native target for local debugging and testing ---

[env:native]
platform = native
build_flags =
    -Wall
    -Wextra
    -std=c++17
    -DNATIVE
test_framework = unity
